// alignment-gen.mjs — commits the alignment table (P4 done-when) from pipeline/qc reports.
// Actuals only (R8): PENDING everywhere until registration + meshing compute real numbers.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => { try { return JSON.parse(fs.readFileSync(path.join(root, p), 'utf8')); } catch { return null; } };
const reg = read('pipeline/qc/registration.json');
const mesh = read('pipeline/qc/meshing.json');

const md = `# ALIGNMENT — auto-generated by scripts/alignment-gen.mjs (actuals only, R8)

| source | master space | method | status | metric |
|---|---|---|---|---|
| brain.glb (gross) | MNI152NLin2009cAsym 1mm | 7-DoF ICP (H2) | ${reg?.status ?? 'UNKNOWN'} | mean ${reg?.mean_surface_distance_mm ?? 'NULL'} mm / p95 ${reg?.p95_distance_mm ?? 'NULL'} mm |
| allen | MNI152NLin2009cAsym 1mm | mirror (H3) + TemplateFlow/ANTs (H1) | ${mesh?.sources?.allen ? 'MESHING_PENDING' : 'UNKNOWN'} | Dice NULL |
| cit168 + amygdala | MNI152NLin2009cAsym 1mm | H1 (assumed aligned ≤1.5mm or ANTs SyN) | MESHING_PENDING | Dice NULL |
| aan-v2 | MNI152 1mm | H1 | MESHING_PENDING | Dice NULL |
| thalamic / hypothalamic | MNI | H1 | MESHING_PENDING | Dice NULL |

Targets (report actuals even if missed): GLB→MNI MSD ≤3mm; atlas→master Dice ≥0.90; ≤1.5mm assumed-aligned gate.
`;
fs.writeFileSync(path.join(root, 'docs', 'ALIGNMENT.md'), md);
console.log('alignment-gen: wrote docs/ALIGNMENT.md (all PENDING)');
