// build-p1.mjs — authors P1 disorder packs (P8). Original paraphrase; DRAFT needs-source; no doses.
// Run: node scripts/build-p1.mjs → content/disorders/p1.json (+ public copy via copy-content).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const D = (id, name, code, circuits, structures, symptoms, tabs, mcqs, tour) => ({
  id, name, code, circuits, structures, symptoms, tabs, mcqs, tour,
  references: ['src.needs-source'], reviewStatus: 'draft',
  claims: [{ id: `clm.${id}-1`, text: `${name} teaching pack (draft schematics).`, evidence: 'emerging', sourceIds: ['src.needs-source'] }],
});

const T = (overview, neuroanatomy, circuits, psychopathology, clinical, differential, investigations, management, neuromodulation, course, pearls, vignette) =>
  ({ overview, neuroanatomy, circuits, psychopathology, clinical, differential, investigations, management, neuromodulation, course, pearls, vignette });

const disorders = [
  D('schizophrenia', 'Schizophrenia and other psychoses', 'F20 (concept)',
    ['circuit.psychosis', 'circuit.mesolimbic-da', 'circuit.triple-network'],
    ['deep.striatum-dorsal', 'ctx.dlpfc', 'deep.hipp', 'ctx.stg'],
    ['delusions', 'auditory hallucinations', 'formal thought disorder', 'avolition'],
    T(
      'Psychosis involves altered reality testing with varied course across individuals.',
      'Structural meta-analytic findings are small on average; cite effect sizes only from sources (pending).',
      'Dorsal striatal dopamine signalling, prefrontal E/I balance and hippocampal-VTA loop are studied (hypotheses).',
      'Delusions map to salience circuits; voices to auditory networks; thought disorder to language circuits (draft).',
      'Clinical picture combines positive, negative and cognitive features with functional impact (paraphrased).',
      'Consider mood psychosis, delirium, substance-induced and neurological causes (paraphrased).',
      'Workup excludes medical mimics; neuroimaging when indicated (paraphrased).',
      'Antipsychotic classes per guidelines; psychosocial rehabilitation alongside (no doses; formulary-check).',
      'ECT considered for catatonia or treatment resistance per guidelines; rTMS/DBS investigational (draft).',
      'Course varies; early intervention and adherence support prognosis (paraphrased).',
      'Viva: salience + dorsal striatum + prefrontal E/I; never state hypotheses as fact.',
      'Original vignette: a young adult with new suspiciousness and voices; workup-first teaching case (draft).'
    ),
    [
      { q: 'Salience circuit substrate in psychosis models?', o: ['Dorsal striatum dopamine signalling', 'Arcuate fasciculus', 'VLPO', 'PAG-RVM'], a: 0, e: 'Draft schematic.' },
      { q: 'Auditory voices network context?', o: ['STG + monitoring circuits', 'V1 only', 'Cerebellar vermis', 'Conus'], a: 0, e: 'Draft schematic.' },
      { q: 'Hippocampal-VTA loop status?', o: ['Hypothesis', 'Established law', 'Disproven', 'Treatment'], a: 0, e: 'Label hypotheses.' },
      { q: 'Cognitive dysmetria circuit?', o: ['Cerebello-thalamo-cortical', 'HPA axis', 'Arcuate', 'Spinothalamic'], a: 0, e: 'Draft schematic.' },
      { q: 'Mesocortical pattern proposed?', o: ['Prefrontal hypodopaminergia', 'Cortical hyperdopaminergia', 'No change', 'Serotonin only'], a: 0, e: 'Draft schematic.' },
      { q: 'NMDA-hypofunction relates to?', o: ['E/I imbalance models', 'Vitamin deficiency', 'Fracture healing', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'First-rank passivity phenomena link?', o: ['Agency circuits (TPJ)', 'Medulla', 'Retina', 'Cochlea'], a: 0, e: 'Draft schematic.' },
      { q: 'Formal thought disorder circuits?', o: ['Language networks', 'Visual cortex only', 'Spinal cord', 'Sinuses'], a: 0, e: 'Draft schematic.' },
      { q: 'Avolition maps toward?', o: ['Reward circuits', 'Optic nerve', 'Cerebellar tonsil', 'Pituitary'], a: 0, e: 'Draft schematic.' },
      { q: 'Differential that mimics psychosis acutely?', o: ['Delirium', 'Myopia', 'Otitis', 'Eczema'], a: 0, e: 'Teaching concept.' },
      { q: 'Catatonia neuromodulation per guidelines?', o: ['ECT considered', 'No options exist', 'Surgery first-line', 'None'], a: 0, e: 'Guideline-check required.' },
      { q: 'Negative symptom example?', o: ['Avolition', 'Fever', 'Rash', 'Polyuria'], a: 0, e: 'Teaching concept.' },
      { q: 'Cognitive domain often affected?', o: ['Executive function', 'Colour vision only', 'Smell only', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Best next step for new psychosis with fever?', o: ['Medical workup first', 'Ignore fever', 'Discharge', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Family psychoeducation role?', o: ['Support adherence/recovery', 'Replace medication', 'Cure alone', 'None'], a: 0, e: 'Teaching concept.' }
    ],
    ['Define psychosis in one line.', 'Name two circuits studied.', 'Localise voices vs delusions.', 'List two differentials.', 'State one ECT indication.', 'Give one viva pearl with hypothesis label.']
  ),
  D('mdd', 'Major depressive disorder', 'F32-F33 (concept)',
    ['circuit.mood', 'circuit.mesolimbic-da', 'circuit.hpa'],
    ['ctx.sgacc', 'deep.amygdala', 'deep.habenula', 'ctx.dlpfc'],
    ['anhedonia', 'psychomotor retardation', 'anxiety', 'insomnia'],
    T(
      'Depression combines low mood or anhedonia with cognitive and vegetative features (paraphrased).',
      'Structural findings are small on average; cite meta-analytic effect sizes only (pending).',
      'Subgenual ACC, amygdala, habenula and prefrontal balance are studied with DLPFC asymmetry (draft).',
      'Anhedonia maps toward reward circuits; retardation toward motor loops (draft).',
      'Clinical features span mood, interest, sleep, appetite, energy and concentration (paraphrased).',
      'Consider bipolarity, medical causes, substances and bereavement context (paraphrased).',
      'Screen thyroid, anaemia and substances where indicated (paraphrased).',
      'Antidepressant classes and psychotherapy per guidelines; no doses here (formulary-check).',
      'rTMS to DLPFC, ECT for severe/psychotic cases per guidelines (draft).',
      'Recurrence is common; maintenance follows guideline algorithms (paraphrased).',
      'Viva: sgACC + habenula + DLPFC asymmetry; anhedonia = reward circuit.',
      'Original vignette: gradual anhedonia with early waking; measurement-based teaching case (draft).'
    ),
    [
      { q: 'Anhedonia maps toward?', o: ['Mesolimbic reward', 'Arcuate', 'Optic radiation', 'Medulla'], a: 0, e: 'Draft schematic.' },
      { q: 'Subgenual ACC role studied?', o: ['Mood regulation node', 'Hearing', 'Balance', 'Smell'], a: 0, e: 'Draft schematic.' },
      { q: 'Habenula proposed role?', o: ['Anti-reward signalling', 'Vision', 'Hearing', 'Taste'], a: 0, e: 'Draft schematic.' },
      { q: 'rTMS target in depression?', o: ['DLPFC', 'Occiput', 'Cerebellar tonsil', 'Conus'], a: 0, e: 'Guideline-check.' },
      { q: 'HPA axis relevance?', o: ['Stress physiology', 'Fracture healing', 'Dental caries', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Psychomotor retardation loops?', o: ['Motor circuits', 'Olfactory only', 'Retinal', 'Cochlear'], a: 0, e: 'Draft schematic.' },
      { q: 'Bipolar screen before antidepressant?', o: ['Always ask mania history', 'Never ask', 'Only in elderly', 'Only in children'], a: 0, e: 'Teaching concept.' },
      { q: 'Psychotic depression option?', o: ['ECT per guidelines', 'No treatment exists', 'Vitamins alone', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'First-line psychotherapy?', o: ['CBT / IPT per guidelines', 'No therapy works', 'Surgery', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Suicide risk assessment?', o: ['Ask directly, safety plan', 'Avoid asking', 'Predict perfectly', 'None'], a: 0, e: 'Principles only; no method detail.' },
      { q: 'Melancholic feature example?', o: ['Early morning waking', 'Fever', 'Rash', 'Polyuria'], a: 0, e: 'Teaching concept.' },
      { q: 'Atypical feature example?', o: ['Mood reactivity', 'Fracture', 'Deafness', 'Blindness'], a: 0, e: 'Teaching concept.' },
      { q: 'Maintenance phase aims?', o: ['Prevent recurrence', 'Cure personality', 'Stop all follow-up', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Medical mimic to exclude?', o: ['Hypothyroidism', 'Myopia', 'Dandruff', 'Caries'], a: 0, e: 'Teaching concept.' },
      { q: 'Anhedonia viva one-liner?', o: ['Reward circuit output', 'Bone growth', 'Hair growth', 'Nail growth'], a: 0, e: 'Draft schematic.' }
    ],
    ['Define depression in one line.', 'Name the mood circuit nodes.', 'Localise anhedonia.', 'List two differentials.', 'State one neuromodulation target.', 'Give one viva pearl.']
  ),
  D('bipolar', 'Bipolar disorder (mania / depression)', 'F31 (concept)',
    ['circuit.mood', 'circuit.mesolimbic-da'],
    ['ctx.vmpfc', 'deep.amygdala', 'ctx.dlpfc'],
    ['elevated mood', 'decreased need for sleep', 'impulsivity', 'anhedonia'],
    T(
      'Bipolar disorder alternates elevated and depressive states with inter-episode recovery (paraphrased).',
      'Structural findings overlap mood-psychosis spectra; cite effect sizes only (pending).',
      'Mania vs depression asymmetry across prefrontal-limbic balance is studied (draft).',
      'Decreased sleep need maps toward arousal circuits; impulsivity toward control circuits (draft).',
      'Mania features elevated mood, energy, sleep loss and risk-taking (paraphrased).',
      'Consider substances, medical causes and unipolar depression course (paraphrased).',
      'Baseline labs/ECG per agent guidelines before mood stabilisers (paraphrased).',
      'Mood stabiliser + atypical classes per guidelines; no doses here (formulary-check).',
      'ECT for severe mania/depression per guidelines (draft).',
      'Relapse prevention hinges on adherence and early-warning plans (paraphrased).',
      'Viva: mania vs depression asymmetry; sleep loss is core.',
      'Original vignette: reduced sleep with over-spending; collateral-first teaching case (draft).'
    ),
    [
      { q: 'Core mania sleep feature?', o: ['Decreased need for sleep', 'Hypersomnia always', 'No change', 'Coma'], a: 0, e: 'Teaching concept.' },
      { q: 'Impulsivity maps toward?', o: ['Control circuits', 'Retina', 'Cochlea', 'Skin'], a: 0, e: 'Draft schematic.' },
      { q: 'Mood stabiliser class?', o: ['Lithium / valproate / atypical per guidelines', 'Antibiotics', 'Antihistamines only', 'None'], a: 0, e: 'Guideline-check; no doses.' },
      { q: 'Antidepressant risk in bipolar?', o: ['Mood switch', 'No risk at all', 'Cures mania', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Psychosis in mania localises?', o: ['Salience + mood circuits', 'Knee joint', 'Elbow', 'Ankle'], a: 0, e: 'Draft schematic.' },
      { q: 'Mixed features mean?', o: ['Both polarities together', 'No symptoms', 'Only anxiety', 'Only sleep'], a: 0, e: 'Teaching concept.' },
      { q: 'Rapid cycling definition context?', o: ['Episode frequency concept', 'Bicycle speed', 'Heart rate', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Baseline test before lithium?', o: ['Renal/thyroid per guidelines', 'No tests needed', 'X-ray foot', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Pregnancy planning needs?', o: ['Preconception review', 'No review needed', 'Stop all care', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Early-warning plan includes?', o: ['Sleep/mood diary', 'No monitoring', 'Only labs', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Depressive pole circuits?', o: ['Mood + reward', 'Optic only', 'Olfactory only', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Substance screen why?', o: ['Mimics/trigger', 'Irrelevant', 'Illegal everywhere', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'ECT role?', o: ['Severe/resistant states', 'Never used', 'First-line always', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Collateral history value?', o: ['Confirms sleep/behaviour change', 'Useless', 'Harmful', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Viva pearl on asymmetry?', o: ['Mania vs depression prefrontal balance', 'Bone asymmetry', 'Hair asymmetry', 'None'], a: 0, e: 'Draft schematic.' }
    ],
    ['Define bipolarity in one line.', 'Name asymmetry concept.', 'Localise impulsivity.', 'List stabiliser classes.', 'State ECT role.', 'Give one viva pearl.']
  ),
  D('ocd', 'OCD and related disorders', 'F42 (concept)',
    ['circuit.cstc'],
    ['ctx.ofc', 'deep.striatum', 'thal.md'],
    ['obsessions', 'compulsions', 'anxiety'],
    T(
      'OCD combines intrusive thoughts with repetitive behaviours relieving distress (paraphrased).',
      'Orbitofronto-striatal findings are small; cite effect sizes only (pending).',
      'Orbitofronto-striatal loop with direct/indirect imbalance is the core model (draft).',
      'Urges map toward habit circuits; anxiety toward threat circuits (draft).',
      'Clinically time-consuming rituals impair function with preserved insight often (paraphrased).',
      'Consider tics, autism-related routines and psychosis (paraphrased).',
      'Assess severity with standard scales; medical workup rarely central (paraphrased).',
      'SSRI + exposure-response prevention per guidelines; no doses (formulary-check).',
      'DBS/rTMS for refractory cases in specialist centres (draft).',
      'Course is often chronic with waxing; ERP sustains gains (paraphrased).',
      'Viva: OFC-striatal loop; ERP is first-line with SSRI.',
      'Original vignette: contamination fears with washing; hierarchy-based teaching case (draft).'
    ),
    [
      { q: 'Core OCD loop?', o: ['Orbitofronto-striatal', 'HPA axis', 'Arcuate', 'Spinothalamic'], a: 0, e: 'Draft schematic.' },
      { q: 'First-line psychotherapy?', o: ['Exposure-response prevention', 'No therapy', 'Surgery first', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Medication class?', o: ['SSRI per guidelines', 'Antibiotics', 'Steroids', 'None'], a: 0, e: 'No doses.' },
      { q: 'Insight is usually?', o: ['Preserved', 'Absent always', 'Coma', 'None'], a: 0, e: 'Teaching concept.' },
      { q: ' tic-related comorbidity?', o: ['Tic disorders', 'Fractures', 'Caries', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Hoarding vs collecting?', o: ['Distress/impairment defines disorder', 'Identical always', 'Never clinical', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Trichotillomania group?', o: ['OCD-related', 'Psychotic', 'Delirium', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Direct vs indirect balance?', o: ['Go/no-go striatal paths', 'Blood groups', 'Bone types', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Refractory option?', o: ['Specialist DBS/rTMS', 'No options', 'Amputation', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Reassurance-seeking role?', o: ['Maintains cycle', 'Cures instantly', 'Irrelevant', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Onset pattern often?', o: ['Gradual waxing', 'Sudden coma', 'Fever only', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Family accommodation?', o: ['Reduce gradually', 'Increase forever', 'Ignore', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Differential with psychosis?', o: ['Insight + ego-dystonicity', 'Identical', 'No difference', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'ERP hierarchy starts?', o: ['Low distress items', 'Hardest item', 'No hierarchy', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Viva one-liner?', o: ['OFC-striatal loop + ERP', 'Bone loop', 'Hair loop', 'None'], a: 0, e: 'Draft schematic.' }
    ],
    ['Define OCD in one line.', 'Name the loop.', 'Localise urges.', 'State first-line therapy.', 'List one refractory option.', 'Give one viva pearl.']
  ),
  D('sud', 'Substance use disorders', 'F10-F19 (concept)',
    ['circuit.mesolimbic-da', 'circuit.hpa'],
    ['bs.vta', 'deep.accumbens', 'deep.amygdala-extended'],
    ['craving', 'anxiety', 'impulsivity', 'insomnia'],
    T(
      'Addiction cycles binge, withdrawal-negative affect and preoccupation-craving stages (paraphrased).',
      'Structural findings vary by substance; cite effect sizes only (pending).',
      'VTA-NAc reward, extended-amygdala stress and habenula anti-reward interact (draft).',
      'Craving maps toward incentive circuits; withdrawal toward stress circuits (draft).',
      'Intoxication vs withdrawal signs differ per substance class (paraphrased).',
      'Consider dual diagnosis and medical complications per substance (paraphrased).',
      'Toxicology, liver and infectious screens where indicated (paraphrased).',
      'Agonist/antagonist/aversive classes per substance guidelines; no doses (formulary-check).',
      'rTMS/DBS investigational for craving (draft).',
      'Relapse is common; contingency and follow-up help (paraphrased).',
      'Viva: three stages + habenula anti-reward.',
      'Original vignette: craving with morning relief drinking; stage-based teaching case (draft).'
    ),
    [
      { q: 'Reward core path?', o: ['VTA → NAc', 'VLPO → cortex', 'Retina → LGN', 'Cochlea → MGN'], a: 0, e: 'Draft schematic.' },
      { q: 'Anti-reward node?', o: ['Habenula', 'Cerebellar tonsil', 'Pineal', 'Conus'], a: 0, e: 'Draft schematic.' },
      { q: 'Withdrawal affect system?', o: ['Extended amygdala stress', 'Arcuate', 'Optic nerve', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Alcohol withdrawal sign?', o: ['Tremor/seizure risk', 'Miosis only', 'Fever never', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Opioid withdrawal sign?', o: ['Mydriasis/piloerection', 'Miosis', 'Coma always', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Stimulant intoxication?', o: ['Mydriasis/agitation', 'Miosis/sedation', 'No signs', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Cannabis withdrawal?', o: ['Irritability/sleep loss', 'No syndrome', 'Coma', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Nicotine replacement role?', o: ['Craving relief', 'Cure alone', 'No role', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Dual diagnosis means?', o: ['SUD + mental illness', 'Two infections', 'Two fractures', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Contingency management is?', o: ['Reward-based therapy', 'Punishment only', 'Surgery', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Wernicke risk in alcohol use?', o: ['Thiamine before glucose', 'No risk', 'Only in elderly', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Craving viva line?', o: ['Incentive salience circuit', 'Bone circuit', 'Hair circuit', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Preoccupation stage?', o: ['Craving/anticipation', 'No stage', 'Only intoxication', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Harm reduction example?', o: ['Needle exchange', 'No measures', 'Isolation', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Follow-up focus?', o: ['Relapse prevention', 'Discharge forever', 'No follow-up', 'None'], a: 0, e: 'Teaching concept.' }
    ],
    ['Define addiction cycle.', 'Name three stages.', 'Localise craving.', 'List withdrawal signs.', 'State one therapy.', 'Give one viva pearl.']
  ),
  D('somatic', 'Somatic symptom disorder', 'F45 (concept)',
    ['circuit.fnd', 'circuit.pain'],
    ['ctx.insula-ant', 'ctx.acc', 'ctx.sma'],
    ['somatic preoccupation', 'anxiety', 'interoceptive disturbance'],
    T(
      'Distressing bodily symptoms with disproportionate thoughts and behaviours (paraphrased).',
      'No diagnostic structural signature; interoception circuits studied (emerging).',
      'Insula-ACC interoceptive and pain-matrix interactions proposed (emerging).',
      'Preoccupation maps toward salience/interoceptive circuits (draft).',
      'Symptoms are genuine and impairing; function matters most (paraphrased).',
      'Rule out medical causes proportionately without over-investigation (paraphrased).',
      'Targeted workup, then regular follow-up visits (paraphrased).',
      'CBT, psychoeducation and antidepressant classes where comorbid (no doses).',
      'No routine neuromodulation; treat comorbidity per guidelines (draft).',
      'Prognosis improves with continuity and function focus (paraphrased).',
      'Viva: genuine symptoms; interoception circuits emerging.',
      'Original vignette: multiple pains with normal workup; function-first teaching case (draft).'
    ),
    [
      { q: 'Key circuit studied?', o: ['Interoceptive insula-ACC', 'Arcuate', 'Optic nerve', 'Conus'], a: 0, e: 'Emerging.' },
      { q: 'Symptoms are?', o: ['Genuine and impairing', 'Feigned always', 'Imaginary only', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Workup approach?', o: ['Proportionate then follow-up', 'Endless scans', 'No exam', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'First-line therapy?', o: ['CBT + psychoeducation', 'Surgery', 'No care', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Comorbid anxiety role?', o: ['Amplifies focus', 'Irrelevant', 'Protective always', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Reassurance pattern?', o: ['Brief relief then return', 'Permanent cure', 'Never sought', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Function focus means?', o: ['Activity scheduling', 'Bed rest forever', 'No activity', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Red-flag duty?', o: ['Re-examine new signs', 'Ignore all', 'Discharge all', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Pain matrix nodes?', o: ['Insula + ACC + thalamus', 'Cochlea only', 'Retina only', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Placebo context?', o: ['Expectation circuitry', 'No biology', 'Magic', 'None'], a: 0, e: 'Emerging.' },
      { q: 'Collateral role?', o: ['Function history', 'Useless', 'Harmful', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Prognosis factor?', o: ['Continuity of care', 'Doctor shopping', 'No follow-up', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Depression screen why?', o: ['Common comorbidity', 'Irrelevant', 'Forbidden', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Note wording matters?', o: ['Validate + plan', 'Dismiss', 'Accuse', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Viva line?', o: ['Genuine + interoception', 'Fake + ignore', 'No circuits', 'None'], a: 0, e: 'Draft.' }
    ],
    ['Define disorder in one line.', 'Name interoceptive nodes.', 'State workup stance.', 'List one therapy.', 'State prognosis factor.', 'Give one viva pearl.']
  ),
  D('conversion', 'Conversion disorder / functional neurological disorder', 'F44 (concept)',
    ['circuit.fnd', 'circuit.motor'],
    ['ctx.sma', 'ctx.tpj', 'ctx.insula-ant'],
    ['conversion motor symptoms', 'conversion sensory symptoms', 'dissociation'],
    T(
      'Neurological-appearing symptoms incompatible with recognised disease patterns (paraphrased).',
      'No diagnostic lesion; limbic-motor interaction models are emerging/hypothesis.',
      'SMA, TPJ agency and insula-ACC circuits proposed (hypothesis).',
      'Motor symptoms map toward voluntary-motor vs agency mismatch (hypothesis).',
      'Diagnosis rests on positive inconsistency signs with examination (paraphrased).',
      'Distinguish from feigning by internal inconsistency, not accusation (paraphrased).',
      'Video/EEG or imaging only as indicated (paraphrased).',
      'Physiotherapy + CBT-informed rehabilitation per guidelines (draft).',
      'No routine neuromodulation (draft).',
      'Early explanation + rehab improves outcome (paraphrased).',
      'Viva: positive signs; agency hypothesis labelled.',
      'Original vignette: give-way weakness with Hoover sign; explanation-first case (draft).'
    ),
    [
      { q: 'Key agency node proposed?', o: ['TPJ', 'Cochlea', 'Retina', 'Skin'], a: 0, e: 'Hypothesis.' },
      { q: 'Motor node proposed?', o: ['SMA', 'Medulla only', 'Conus', 'None'], a: 0, e: 'Hypothesis.' },
      { q: 'Diagnosis rests on?', o: ['Positive inconsistency signs', 'Accusation', 'No exam', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Hoover sign shows?', o: ['Inconsistency', 'Fracture', 'Infection', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'First step?', o: ['Clear explanation', 'Confrontation', 'Discharge', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Rehab includes?', o: ['Physiotherapy + CBT-informed', 'Bed rest years', 'No rehab', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Evidence level?', o: ['Emerging/hypothesis', 'Law', 'Disproven', 'None'], a: 0, e: 'Label honestly.' },
      { q: 'Seizure-like events workup?', o: ['Video-EEG when indicated', 'Never needed', 'Always surgery', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Sensory signs?', o: ['Splitting midline patterns', 'Dermatomal always', 'No signs', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Comorbidity screen?', o: ['Anxiety/depression', 'No screen', 'Only labs', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Prognosis factor?', o: ['Early rehab', 'Delay years', 'No care', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Family role?', o: ['Reinforce function', 'Punish symptoms', 'Ignore patient', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Interoception node?', o: ['Insula', 'Arcuate', 'Optic nerve', 'None'], a: 0, e: 'Hypothesis.' },
      { q: 'Documentation should?', o: ['Describe signs objectively', 'Accuse', 'Omit exam', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Viva line?', o: ['SMA-TPJ agency hypothesis', 'Bone hypothesis', 'Hair hypothesis', 'None'], a: 0, e: 'Hypothesis.' }
    ],
    ['Define FND in one line.', 'Name two nodes.', 'State one positive sign.', 'Give explanation line.', 'List rehab duo.', 'Give viva pearl with label.']
  ),
  D('anxiety', 'Anxiety disorders (GAD / panic / social)', 'F40-F41 (concept)',
    ['circuit.fear-anxiety'],
    ['deep.amygdala-bla', 'deep.amygdala-cea', 'ctx.vmpfc', 'bs.pag'],
    ['fear', 'anxiety', 'anxiety', 'insomnia'],
    T(
      'Anxiety disorders share excessive fear/worry with avoidance and arousal (paraphrased).',
      'No diagnostic structural signature; threat-circuit function studied (emerging).',
      'BLA-CeA, vmPFC extinction, BNST sustained anxiety and PAG output (draft).',
      'Panic maps toward PAG + arousal; social toward evaluation circuits (draft).',
      'GAD is broad worry; panic is abrupt surges; social is scrutiny fear (paraphrased).',
      'Consider medical (thyroid), substances and depression comorbidity (paraphrased).',
      'Vitals, thyroid and substance review where indicated (paraphrased).',
      'SSRI/SNRI + CBT per guidelines; no doses (formulary-check).',
      'No routine neuromodulation (draft).',
      'Course tends to persist without treatment; CBT gains hold (paraphrased).',
      'Viva: BLA→CeA→PAG; vmPFC extinction; BNST sustained.',
      'Original vignette: panic-like surges with normal ECG; exposure-based case (draft).'
    ),
    [
      { q: 'Fear output path?', o: ['BLA → CeA → PAG', 'VLPO → cortex', 'Retina → LGN', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Extinction node?', o: ['vmPFC', 'Cochlea', 'Conus', 'Pineal'], a: 0, e: 'Draft schematic.' },
      { q: 'Sustained anxiety node?', o: ['BNST', 'Arcuate', 'Optic nerve', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Panic arousal nuclei?', o: ['LC + hypothalamus', 'VLPO only', 'None', 'Bones'], a: 0, e: 'Draft schematic.' },
      { q: 'First-line therapy?', o: ['CBT', 'Surgery', 'No therapy', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Medication class?', o: ['SSRI/SNRI', 'Antibiotics', 'Steroids', 'None'], a: 0, e: 'No doses.' },
      { q: 'Benzodiazepine stance?', o: ['Short-term caution', 'First-line chronic', 'Never any use', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Medical mimic?', o: ['Hyperthyroidism', 'Myopia', 'Caries', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Social anxiety core?', o: ['Scrutiny fear', 'Fever', 'Rash', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Exposure principle?', o: ['Graded hierarchy', 'Flooding always', 'Avoidance forever', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Panic attack peak?', o: ['Minutes', 'Days', 'Months', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'GAD worry scope?', o: ['Multiple domains', 'Single topic only', 'No worry', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Comorbidity screen?', o: ['Depression', 'No screen', 'Only X-ray', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Relaxation role?', o: ['Adjunct skill', 'Cure alone', 'Harmful', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Viva line?', o: ['BLA-CeA-PAG + vmPFC', 'Bone-PAG', 'Hair-PAG', 'None'], a: 0, e: 'Draft schematic.' }
    ],
    ['Define anxiety in one line.', 'Name fear path.', 'State extinction node.', 'List first-line duo.', 'Name one mimic.', 'Give viva pearl.']
  ),
  D('ptsd', 'Post-traumatic stress disorder', 'F43 (concept)',
    ['circuit.fear-anxiety', 'circuit.hpa'],
    ['deep.amygdala', 'ctx.vmpfc', 'deep.hipp'],
    ['fear', 'anxiety', 'dissociation', 'insomnia'],
    T(
      'PTSD follows trauma with re-experiencing, avoidance, arousal and mood shifts (paraphrased).',
      'No diagnostic structural signature; threat-memory circuits studied (emerging).',
      'Amygdala reactivity, vmPFC/hippocampal context and HPA tone interact (draft).',
      'Flashbacks map toward memory-threat coupling; numbing toward regulation (draft).',
      'Screen trauma type, dissociation and comorbidity sensitively (paraphrased).',
      'Distinguish from depression, TBI and prolonged grief context (paraphrased).',
      'Medical workup only as indicated; safety first (paraphrased).',
      'Trauma-focused CBT/EMDR + SSRI classes per guidelines; no doses (formulary-check).',
      'No routine neuromodulation (draft).',
      'Early evidence-based care improves trajectory (paraphrased).',
      'Viva: context extinction via vmPFC-hippocampus.',
      'Original vignette: nightmares after event with avoidance; phased teaching case (draft).'
    ),
    [
      { q: 'Context node?', o: ['Hippocampus + vmPFC', 'Cochlea', 'Conus', 'Pineal'], a: 0, e: 'Draft schematic.' },
      { q: 'First-line therapy?', o: ['Trauma-focused CBT/EMDR', 'Surgery', 'No therapy', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Medication class?', o: ['SSRI per guidelines', 'Antibiotics', 'Steroids', 'None'], a: 0, e: 'No doses.' },
      { q: 'Dissociation maps toward?', o: ['Regulation circuits', 'Bones', 'Hair', 'None'], a: 0, e: 'Emerging.' },
      { q: 'HPA relevance?', o: ['Stress tone', 'Fracture healing', 'Dental', 'None'], a: 0, e: 'Draft schematic.' },
      { q: 'Avoidance maintains?', o: ['Symptoms', 'Cure', 'Nothing', 'Bones'], a: 0, e: 'Teaching concept.' },
      { q: 'Screen first?', o: ['Safety + trauma type', 'No screen', 'Only labs', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Comorbidity common?', o: ['Depression/substance use', 'Never', 'Only fever', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Nightmares relate to?', o: ['Memory consolidation', 'Diet only', 'Shoes', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Grounding technique role?', o: ['Present-moment anchor', 'Cure alone', 'Harmful', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Prolonged grief differs by?', o: ['Loss context', 'Identical', 'No difference', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'TBI overlap?', o: ['Amnesia/confusion screen', 'Irrelevant', 'Same always', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Follow-up focus?', o: ['Function + symptoms', 'Discharge', 'No care', 'None'], a: 0, e: 'Teaching concept.' },
      { q: 'Debriefing stance?', o: ['Not routine single-session', 'Mandatory always', 'Forbidden topic', 'None'], a: 0, e: 'Guideline-check.' },
      { q: 'Viva line?', o: ['Context extinction circuit', 'Bone circuit', 'Hair circuit', 'None'], a: 0, e: 'Draft schematic.' }
    ],
    ['Define PTSD in one line.', 'Name context nodes.', 'State first-line therapy.', 'List one differential.', 'State safety priority.', 'Give viva pearl.']
  )
];

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
fs.writeFileSync(path.join(root, 'content', 'disorders', 'p1.json'), JSON.stringify({ reviewStatus: 'draft', count: disorders.length, disorders }, null, 2));
console.log(`build-p1: ${disorders.length} P1 packs written`);
