// coverage-gen.mjs — auto-generates docs/COVERAGE.md (P4). Honest: present-gross vs missing only;
// exact/registered flips require meshing.json + registration.json PASS (both PENDING in P4).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manPath = path.join(root, 'public', 'atlas', 'core-anatomy', 'manifest.json');
const outPath = path.join(root, 'docs', 'COVERAGE.md');

const PROBES = [
  ['cortex', 'DLPFC'], ['cortex', 'dorsolateral'], ['cortex', 'Broca'], ['cortex', 'subgenual'],
  ['cortex', 'entorhinal'], ['cortex', 'Brodmann'],
  ['limbic', 'CA1'], ['limbic', 'dentate gyrus'], ['limbic', 'BLA'], ['limbic', 'BNST'],
  ['limbic', 'accumbens core'], ['limbic', 'claustrum'], ['limbic', 'PVN'],
  ['limbic', 'pituitary'], ['limbic', 'pineal'],
  ['thalamus', 'LGN'], ['thalamus', 'pulvinar'], ['thalamus', 'reticular nucleus'],
  ['brainstem', 'superior colliculus'], ['brainstem', 'red nucleus'], ['brainstem', 'PAG'],
  ['brainstem', 'locus coeruleus'], ['brainstem', 'dorsal raphe'],
  ['cerebellum', 'dentate nucleus'], ['cerebellum', 'fastigial'], ['cerebellum', 'tonsil'],
  ['pathways', 'genu'], ['pathways', 'splenium'], ['pathways', 'arcuate fasciculus'],
  ['pathways', 'SLF'], ['pathways', 'uncinate'], ['pathways', 'fornix'],
  ['pathways', 'stria terminalis'], ['pathways', 'medial forebrain'], ['pathways', 'optic radiation'],
  ['pathways', 'medial lemniscus'], ['pathways', 'spinothalamic'],
  ['csf', 'aqueduct'], ['csf', 'choroid'], ['csf', 'falx'], ['csf', 'tentorium'],
  ['vascular', 'PComm'], ['vascular', 'lenticulostriate'], ['vascular', 'vein of Galen'],
  ['vascular', 'straight sinus'], ['vascular', 'cavernous sinus'],
  ['spinal', 'conus'], ['spinal', 'dorsal horn'], ['spinal', 'DRG'], ['spinal', 'Adamkiewicz'],
];

const man = JSON.parse(fs.readFileSync(manPath, 'utf8'));
const labels = man.nodes.map((n) => `${n.label} ${n.name}`.toLowerCase());

let rows = [];
for (const [sys, probe] of PROBES) {
  const hits = labels.filter((l) => l.includes(probe.toLowerCase())).length;
  rows.push(`| ${sys} | ${probe} | ${hits > 0 ? `present-gross (${hits})` : 'missing'} | ${hits > 0 ? 'registered-at-best' : 'missing'} | ${hits > 0 ? 'base manifest' : 'P4 atlas-exact'} |`);
}

const md = `# COVERAGE — auto-generated by scripts/coverage-gen.mjs (do not hand-edit)

Gross nodes audited: ${man.nodes.length}. Fidelity today: present-gross = registered-at-best (MNI PENDING);
subdivisions flip to exact/registered only with meshing + registration PASS. Missing = honest gap (R2).

| system | structure probe | status | fidelity | source |
|---|---|---|---|---|
${rows.join('\n')}
`;
fs.writeFileSync(outPath, md);
console.log(`coverage-gen: ${rows.length} probes, ${rows.filter((r) => r.includes('missing')).length} missing → docs/COVERAGE.md`);
